import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'translateToArabic'
})
export class TranslateToArabicPipe implements PipeTransform {
  transform(englishText: string | number,languageFactor:string | number): any {
    const translations = {
      //account-list
      'Accounts': 'الحسابات',
      'Number': 'الرقم',
      'Name': 'الأسم',
      'Type': 'النوع',
      'Parent': 'الأصل',
      'Entity': 'الجهة',
      'Project': 'المشروع',
      'Vendors':'المصنعين',
      'Add': 'إضافة',
      'Search': 'بحث',
      // add-account
      'Cancel': 'إلغاء',
      'Save': 'حفظ',
      'Parent Acount': 'أصل الحساب',
      'Account Type': 'نوع الحساب',
      'Required': 'مطلوب',
      'Account Name': 'أسم الحساب',
      'Edit Account': 'تعديل الحساب',
      'Add Account': 'إضافة حساب',
      'No Parent': 'بدون أصل',
      //sideBar
      'Journals': 'المجلات',
      'Trial Balance': 'ميزان المراجعة',
      'Account Statement': 'كشف الحساب',
      'Financial Transactions': 'المعاملات المالية',
      'Home': 'الصفحة الرئيسية',
      'Financial Accounts': 'الحسابات المالية',
      //Transaction-list
      'Transactions': 'المعاملات',
      'Transaction': 'المعاملة',
      'Description': 'تفاصيل',
      'Currency': 'العملة',
      'Entity Type': 'نوع الجهة',
      'Journal': 'المجلات',
      'Date': 'التاريخ',
      //Transaction-add
      'Total credit and total debit must be equal': 'مجموع المدين يلزم أن يساوي مجموع الدائن',
      'Debit': 'مدين',
      'Credit': 'دائن',
      'Add New Row': 'إضافة صف جديد',
      'Delete': 'حذف',
      'Account': 'حساب',
      'Transaction Detials': 'تفاصيل المعاملة',
      'Transaction Date': 'تاريخ المعاملة',
      'Transaction Header': 'معلومات المعاملة',
      'Add Transactions': 'إضافة معاملات',
      'entries': 'سجل',
      'of': 'من',
      'to': 'إلى',
      'Showing': 'عرض',
      //journals-list
      'Code': 'الكود',
      //journals-add
      'Name should be more than 3 character': 'يجب إدخال ٣ حروف أو أكثر',
      'Edit Journal': 'تعديل المجلة',
      'Add Journal': 'إضافة مجلة',
      //languages
      'Language': 'اللغة',
      'Search keyword': 'كلمة البحث',
      //trial balance
      'To Date': 'إلى يوم',
      'From Date': 'من يوم',
      'Total': 'الإجمالي',
      'Duration End Balance': 'رصيد نهاية المدة',
      'Duration Start Balance': 'رصيد بداية المدة',
      'Duration from ': 'المدة من',
      'Trial Balance print view within duration': 'عرض ميزان المراجعة خلال المدة',
      'Art Company': 'شركة آرت',
      'Credit Total': 'إجمالي الدائن',
      'Debit Total': 'إجمالي المدين',
      'Credit During Duration': 'الدائن خلال المدة',
      'Debit During Duration': 'المدين خلال المدة',
      'Credit Befor Duration': 'الدائن قبل المدة',
      'Debit Befor Duration': 'المدين قبل المدة',
      'Account ID': 'رقم الحساب',
      // Account statment
      'Transaction ID': 'رقم المعاملة',
      'Balance': 'ميزان',
      'To Date:': ': إلى يوم',
      'From Date:': ': من يوم',
      'Account Name:': ': أسم الحساب',
      'Account Number': ': رقم الحساب',
      'Created Date': 'تاريخ الإنشاء',
      // numbers
      '0': '٠',
      '1': '١',
      '2': '٢',
      '3': '٣',
      '4': '٤',
      '5': '٥',
      '6': '٦',
      '7': '٧',
      '8': '٨',
      '9': '٩',

      '{last}': 'النهاية',
      // users
      'Phone Number': 'رقم الهاتف',
      'Email': 'البريد',
      'Company Users': 'مستخدمين الشركة',
      'All Users': 'كل المستخدمين',
      'User Name': 'أسم المستخدم',
      'Image': 'الصورة',
      'Users': 'المستخدمين',
      //add user
      'Profile Picture': 'الصورة الشخصية',
      'Passwords do not match': 'كلمتا المرور غير متطابقتان',
      'Password Confirmation': 'تأكيد كلمة المرور',
      'Password should be more than 6 character': 'كلمة المرور يجب أن تحتوي على ٦ حروف على الأقل',
      'Password': 'كلمة المرور',
      'Email address is already exsits': 'هذا الحساب موجود بالفعل',
      'Email is invalid': 'الحساب غير صالح',
      'User name should be more than 3 character': 'أسم المستخدم يجب أن يحتوي على ٣ حروف على الأقل ',
      'Edit User': 'تعديل المستخدم',
      'Add User': 'إضافة مستخدم',
      'Select Role': 'اختر دور',
      //companies List
      'Location': 'الموقع',
      'Phone': 'الهاتف',
      'Companies': 'الشركات',
      'Logo': 'الشعار',
      //add company
      'Company name should be more than 3 character': 'أسم الشركة يجب أن يحتوي على ٣ حروف على الأقل ',
      'Company Name': 'أسم الشركة',
      'Edit Company': 'تعديل الشركة',
      'Add Company': 'إضافة شركة',
      //entity List
      'Entities': 'الجهات',
      'Beneficiary': 'المستفيد',
      'Employee': 'موظف',
      'Vendor': 'مصنع',
      'Arabic Name': 'الأسم بالعربي',
      'English Name': 'الأسم بالإنجليزي',
      'Legal Name': 'الأسم القانوني',
      //add entity
      'Role In Company': 'دور في الشركة',
      'Company Contacts': 'جهات الاتصال في الشركة',
      'Invalid Phone Number': 'رقم هاتف غير صالح',
      'Phone Numbers': 'أرقام الهاتف',
      'Invalid Email': 'بريد إلكتروني غير صالح',
      'Web Data': 'بيانات الويب',
      'Gender': 'الجنس',
      'Morital Status': 'الحالة الزواجية',
      'Birth Date': 'تاريخ الميلاد',
      'Passport ID': 'رقم الجواز',
      'National ID': 'الرقم القومي',
      'Personal Data': 'بيانات شخصية',
      'Lootcom Date': 'تاريخ إصدار السجل التجاري',
      'Start date must be before end date.': 'يجب أن يكون تاريخ البدء قبل تاريخ الانتهاء',
      'Tax Card End Date': 'تاريخ انتهاء البطاقة الضريبة',
      'In Valid Commercial No.': 'رقم تجاري غير صالح',
      'Commercial No.': 'الرقم السجل التجاري',
      'Attatchments': 'المرفقات',
      'Tax Reg No': 'رقم البطاقة الضريبية',
      'Commercial No': 'رقم السجل التجاري',
      'Tax Card Start Date': 'تاريخ بدء بطاقة الضريبة',
      'Invalid Tax Reg No.': 'رقم تسجيل ضريبي غير صالح',
      'Tax Reg No.': 'رقم التسجيل الضريبي',
      'Start Date': 'تاريخ البدء',
      'Company Data': 'بيانات الشركة',
      'Street Line': 'سطر الشارع',
      'City': 'المدينة',
      'Country': 'الدولة',
      'Address': 'العنوان',
      'Role Classification': 'تصنيف الدور',
      'Is My Entity?': 'هل هي جهتي؟',
      'Client': 'عميل',
      'Is Client?': 'عميل؟',
      'Is Supplier?': 'مورد؟',
      'Picture': 'الصورة',
      'Select Entity Type': 'اختر نوع الجهة',
      'Select Nationality': 'اختر الجنسية',
      'Add Entity': 'إضافة جهة',
      'Edit Entity': 'تحرير الجهة',
      'URL': 'الرابط',
      'Maximum Phone Number length is 15 digits': 'الهاتف يجب أن يحتوي على ١٥ رقم على الأكثر',
      'Main Entity Information': 'المعلومات الأساسية للجهة',
      'Entity Type:': 'نوع الجهة: ',
      'Nationality:': 'الجنسية: ',
      'Nationality': 'الجنسية',
      'Legal Name:': 'الأسم القانوني: ',
      'Arabic Name:': 'الأسم بالعربية: ',
      'English Name:': 'الأسم بالإنجليزية: ',
      'Code:': 'الكود: ',
      'Lootcom Date:': 'تاريخ إصدار السجل التجاري: ',
      'Tax Card End Date:': 'تاريخ إنتهاء البطاقة الضريبية: ',
      'Tax Card Start Date:': 'تاريخ بدء البطاقة الضريبية: ',
      'Commercial No:': 'رقم السجل التجاري: ',
      'Tax Reg No:': 'رقم التسجيل الضريبي: ',
      'Tax Reg No Already Exist': 'رقم التجيل الضريبي مسجل بالفعل',
      'National ID Already Exist': 'الرقم القومي مسجل بالفعل',
      'Start Date:': 'تاريخ البدء: ',
      //roles List
      'Role name should be more than 3 character': 'أسم الدور يجب أن يحتوي على ٣ حروف على الأقل ',
      'Role name': 'أسم الدور',
      'Edit Role': 'تعديل الدور',
      'Add Role': 'إضافة دور',
      'Roles': 'الأدوار',
      //units list
      'Symbol': 'الرمز',
      'Unit Type': 'نوع الوحدة',
      'Unit Name': 'أسم الوحدة',
      'Units': 'الوحدات',
      //units list
      'Unit': 'الوحدة',
      'Resources': 'الواردات',
      'Resource Type': 'نوع الوارد',
      'Is Group ?': 'هل هي جهة ؟',
      //add resource
      'Select Parent Resource': 'اختر أصل الوارد',
      'Select Unit': 'اختر الوحدة',
      'Select Resource Type': 'اختر نوع الوارد',
      'Edit Resource': 'تعديل الوارد',
      'Add Resource': 'إضافة وارد',
      //units list
      'Choose company to continue': 'اختر شركة للإستمرار',
      'Forget Password': 'تذكر كلمة المرور',
      'Passwored is required': 'كلمة المرور غير صالحة',
      'Please, enter valid email address': 'من فضلك أدخل عنوان بريد صالح',
      'Email is required': 'الحساب مطلوب',
      'Sign in': 'سجل الدخول ',
      // contractsList
      'End Date': 'تاريخ الانتهاء',
      'Main Contract': 'العقد الأساسي',
      'Third Entity': 'الجهة الثالثة',
      'Second Entity': 'الجهة الثانية',
      'First Entity': 'الجهة الأولى',
      'My Company Order': 'طلب شركتي',
      'Person Contact': 'الجهة الشخصية',
      'Persons Contacts': 'الجهات الشخصية',
      'Category': 'الفئة',
      'Contract Type': 'نوع العقد',
      'Status': 'الحالة',
      'Contracts': 'العقود',
      'BOQ': 'المقايسة',
      'Contract Name': 'اسم العقد',
      'Contract Code': 'كود العقد',
      // main
      'Main App': 'التطبيق الرئيسي',
      // tickets
      'Send Request': 'أرسل الطلب',
      'Select Module Name': 'أختر أسم النظام',
      'ADD AN ATTACHMENT': 'أختر ملف',
      // login
      'Register':'سجل',
      'Module':'التطبيق',
      'Address Line':'العنوان',
      'Users No.':'عدد المستخدمين',
      'Warehouses No.':'عدد المخازن',
      'Industry':'الصناعة',
      'Registration':'التسجيل',
      'Confirm Password':'تأكيد كلمة المرور',
      'Select Company':'أختر شركة',
      'Sign In':'تسجيل الدخول',
      'User Name is required':'أسم المستخدم مطلوب',
      'Company Name is required':'أسم الشركة مطلوب',
      //trails
      'Companies Count :':'عدد الشركات : ',
      'Warehouses Count :':'عدد المخازن : ',
      'Users Count :':'عدد المستخدمين : ',
      //subscriptions
      'Email :': 'البريد إلكتروني',
      'phone' : 'رقم الهاتف',
      'countryName':'اسم المدينة',
      'usersCount':'عدد الاعضاء',
      'companiesCount':'عدد الشركات',
      'warehousesCount':'عدد المخازن',
      'subscriptionName':'اسم العضوية',
      'All Subscriptions' : 'كل  الاشتركات',
      'industryName' : 'اسم المجال',
      // payment requests
      'My Requests':'طلباتي',

      'Amount':'المبلغ',
      'Required Date':'التاريخ المطلوب',
      'Payment Methods':'طرق الدفع',
      'Requested Date':'تاريخ الطلب',
      'Approved Amount':'المبلغ المسموح',
      'Requested Amount':'المبلغ المطلوب',
      //Technical Support
      'Sent Date':'تاريخ البدء',
      'Sent by':'أرسل بواسطة',
      'Subject':'الموضوع',
      'Suggestion':'الإقتراحات',
      'Issues':'المشكلات',
      'Clear':'تنظيف',
      'Module Name':'أسم التطبيق',
      'Technical Support':'الدعم الفني',
      //Versions
      'Bug':'المشكلة',
      'Feature':'الميزة',
      'Versions':'الاصدارات',
      'Release No':'رقم الاصدار',
      'Release Date':'تاريخ الاصدار',
      'Versions Reports':'تقارير الاصدارات',
      'All Versions':'كل الاصدارات',
      'Payment Request':'طلب الدفع',
      'Resource':'الخامة',
      'Approved By':'موافق عليه من',
      'Requested Quantity':'الكميو المطلوبة',
      'Approved Quantity':'الكمبة الموافق عليها',
      'Quantity':'الكمية',
      'Edit':'تعديل',
      'Position':'المكان',
      'Group':'المجموعة',
      'User':'المستخدم',
      'Add Attachments':'إضافة مرفقات',
      'Reject':'رفض',
      'Approve':'موافقة',
      'Filter Mode':'وضع التنقية',
      'Payment Request Categories':'فئات طلبات الدفع',
      'Pay':'دفع',
      'Released By':'أصدر بواسطة',
      'Target Payment Date':'التاريخ المحدد للدفع',
      'Requested By':'مطلوب بواسطة',
      'Pay To':'الدفع إلى',
      'Priority Mode':'وضع الترتيب',
      'Configurations History':'تاريخ التكوينات',
      'Needs Request Categories':'فئات طلبات الإحتياج',
      'Add Category':'إضافة فئة',
      'Total credit and total debit must be equal to the main total Amount': 'مجموع المدين او مجموع الدائن يجب أن يساوي المبلغ الكلي',
      'Income Classification':'تصنيف الواردات',
      'Expenses Classification':'تصنيف المصروفات',
      'Add Income Classification':'إضافة تصنيف وارد',
      'Add Expenses Classification':'إضافة تصنيف مصروف',
      'Edit Income Classification':'تعديل تصنيف الواردات',
      'Edit Expenses Classification':'تعديل تصنيف المصروف',
      'Active Classification':'نشط',
      'Expenses':'المصروفات',
      'Transaction Preview':'معاينة تفاصيل القيد',
      'Receivable Cheque':'شيك مستحق القبض',
      'Payable Cheque':'شيك قابل الدفع',
      'Processed':'معالج',
      'Deposited':'مودع',
      'Collected':'محصل',
      'Delivered':'مرسل',
      'Description :':'التفاصيل :',
      'Classification :':'التصنيف :',
      'Amount :':'المبلغ :',
      'Date :':'التاريخ :',
      'Time :':'الوقت :',
      'Code :':'الكود :',
      'Supplier :':'المورد :',
      'Transfer No :':'رقم التحويل :',
      'Cheque No :':'رقم الشيك :',
      'Treasury :':'الخزنة :',
      'Payment Method :':'طريقة الدفع :',
      'Client:': 'العميل: ',
      'Project:': 'المشروع: ',
      'Treasury:': 'الخزنة: ',
      'Cost Center:': 'مركز التكلفة: ',
      'Classification:': 'التصنيف: ',
      'Income Code:': 'الكود: ',
      'Remaining :': 'المتبقي: ',
      'Income Time:': 'التاريخ: ',
      'Income Date:': 'الوقت: ',
      'Multi Projects & Cost Center Allocations':'تعدد تخصيصات المشاريع ومراكز التكلفة',
      'Select Method':'أختر الطريقة',
      'Supplier':'المورد',
      'Incomes':'الإرادات',
      'Income Header':'عنوان الإراد',
      'Attachments':'المرفقات',
      'Outgoing Header':'عنوان المصروف',
      'Edit Outgoing':'تعديل المصروف',
      'Add Outgoing':'إضافة مصروف',
      'Edit Income':'تعديل الإيراد',
      'Add Income':'إضافة الإيراد',
      'Company Activity':'نشاط الشركة',
      'View':'عرض',
      'Permissions':'التصريحات',
      'Groups':'المجموعات',
      'Need Requests':'طلبات الاحتياج',
      'Shipped':'تم الشحن',
      'Document':'وثائق',
      'Document Category':'فئة الوثيقة',
      'Requests':'الطلبات',
      'Header':'العنوان',
      'Add Requests':'إضافة طلبات',
      'Details':'التفاصيل',
      'Limits':'الحدود',
      'History':'القديم',
      'Active':'المتاح',
      'Show Credits':'عرض الأرصدة',
      'User Information' : 'معلومات المستخدم',
      'Employee Information' : 'معلومات الموظف',
      'Branch' : 'الفرع',
      'Department': 'القسم',
      'Hire Date': 'تاريخ التوظيف',
      'Job Title': 'الوظيفة',
      'Role':'الدور',
      'Change Image': 'تغيير الصورة',
      'Privileges': 'الصلاحيات',
      'Add Group' :'اضافة مجموعة',
      'Out of budget': 'خارج الميزانية',
      'In budget': 'داخل الميزانية',
      'Requests Approval' : 'طلبات الموافقة',
      'Remaining Balance': 'المتبقي من الحساب',
      'Filter By' : 'تصفية حسب',
      'Duration' : 'المدة',
      'Requests Paying' : 'طلبات الدفع',
      'Approved Paid' : 'الموافقة والدفع',
      'User Profile' : 'ملف المستخدم',
      'Your Requsts' : 'طلباتك',
      'Change Password' : 'تغيير كلمة المرور',
      'Logout' : 'تسجيل الخروج',
      'Governorates' : 'المحافظات',
      'Governorate' : 'المحافظة',
      'Countries' : 'الدول',
      'Cities' : 'المدن',
      'Districts' : 'الأحياء',
      'District' : 'الحي',
      'ISOCode' : 'كود البلد',
      'Locations' : 'الموقع',
      'Longitude' : 'خط الطول',
      'Latitude' : 'خط العرض',
      'Branches' : 'الفروع',
      'Positions' : 'المناصب',
      'Tree' : 'الهيكل',
      'Prefix': 'البادئة',
      'Page Type': 'نوع الصفحة',
      'Include Year': 'تضمين السنة',
      'Account Level': 'مستوى الحساب',
      'Select a Page Type': 'اختر نوع الصفحة',
      'Configurations Log': 'سجل الاعدادت',
      'Permission': 'التصريحات',
      'Company Structure': 'هيكل الشركة',
      'Categories': 'التصنيفات',
      'Compaines': 'الشركات',
      'Auto Codes' : 'الأكواد التلقائية',
      'Auto Code' : 'الأكواد التلقائية',
      'User Groups' : 'مجموعات المستخدمين',
      'Add User Group' : 'إضافة مجموعة مستخدم',
      'Edit User Group' : 'تعديل مجموعة مستخدم',
      'Delete User Group' : 'حذف مجموعة مستخدم',
      'Download' : 'تحميل',
      'Export Options' : 'خيارات التصدير',
      'Select Format' : 'اختر الصيغة',
      'Export as PDF' : 'تصدير كـ PDF',
      'Export as Excel' : 'تصدير كـ Excel',
      'Select Language' : 'اختر اللغة',
      'Arabic' : 'عربي',
      'English' : 'إنجليزي',
      'Export' : 'تصدير',
      // Additional translations for list pages
      'Yellow Cards' : 'البطاقات الصفراء',
      'Credit Cards' : 'بطاقات الائتمان',
      'Bank Accounts' : 'الحسابات البنكية',
      'Breakdown' : 'التفقيطة',
      'Phones' : 'الهواتف',
      'Wallets' : 'المحافظ',
      'Traders' : 'التجار',
      'Transaction Fees' : 'رسوم المعاملات',
      'E-Transactions-System' : 'نظام المعاملات الإلكترونية',
      'Sign Out' : 'تسجيل الخروج',
      'Select' : 'اختر',
      'Supports' : 'الدعم',
      'Select status' : 'اختر الحالة',
      'Select type' : 'اختر النوع',
      'Notes' : 'ملاحظات',
      'Enter notes' : 'أدخل ملاحظات',
      'New Transaction': 'معاملة جديدة',
      'No data available' : 'لا توجد بيانات متاحة',
      'Pending': 'قيد الانتظار',
      'Completed': 'مكتمل',
      'Failed': 'فشل',
      'Total Amount': 'المبلغ الإجمالي',
      // Login page translations
      'Email or Username is required' : 'البريد الإلكتروني أو اسم المستخدم مطلوب',
      'Welcome to ET System' : 'مرحباً بك في نظام المعاملات الإلكترونية',
      
      // Account Type Enum translations
      ' Wallet': 'محفظة',
      ' Bank Account': 'حساب بنكي',
      ' Yellow Card': 'بطاقة صفراء',
      ' Credit Card': 'بطاقة ائتمان',
      ' Trader': 'تاجر',
      
      // Transaction Type Enum translations
      ' Deposit': 'إيداع',
      ' Withdrawal': 'سحب',
      ' Transfer': 'تحويل',
      ' Payment': 'دفع',
      ' Refund': 'استرداد',
      ' Internal Transfer': 'تحويل داخلي',
      
      // Channel Type Enum translations
      ' ATM': 'صراف آلي',
      ' Instapay': 'إنستاباي',
      ' Fawry': 'فوري',
      ' Wallet Providor': 'برنامج محفظة',
      ' POS': 'نقطة بيع',
      ' Fawry Machine': 'مكينة فوري',
      'Fawry Machines': 'مكينات فوري',
      
      // Adjustments-related translations
      'Adjustments': 'التعديلات',
      'Select Adjustments': 'اختر التعديلات',
      'Select adjustments to apply': 'اختر التعديلات للتطبيق',
      'Base Amount': 'المبلغ الأساسي',
      'Total Increase': 'إجمالي الزيادة',
      'Total Decrease': 'إجمالي النقصان',
      'Net Amount': 'المبلغ الصافي',
      'Fill in transaction details to see preview': 'املأ تفاصيل المعاملة لرؤية المعاينة',
      'Applied Adjustments': 'التعديلات المطبقة',
      'Transaction Details': 'تفاصيل المعاملة',
      'Transaction Information': 'معلومات المعاملة',
      'Transaction Number:': 'رقم المعاملة:',
      'Transaction Date:': 'تاريخ المعاملة:',
      'Transaction Type:': 'نوع المعاملة:',
      'Channel:': 'القناة:',
      'Reference Number:': 'الرقم المرجعي:',
      'Account Information': 'معلومات الحساب',
      'Account Type:': 'نوع الحساب:',
      'Account Reference:': 'مرجع الحساب:',
      'Recipient Information': 'معلومات المستلم',
      'Recipient Account Type:': 'نوع حساب المستلم:',
      'Recipient Reference:': 'مرجع المستلم:',
      'Financial Details': 'التفاصيل المالية',
      'Base Amount:': 'المبلغ الأساسي:',
      'Total Increase:': 'إجمالي الزيادة:',
      'Total Decrease:': 'إجمالي النقصان:',
      'Net Amount:': 'المبلغ الصافي:',
      'Back to List': 'العودة للقائمة',
      'Transaction not found': 'المعاملة غير موجودة',
      'Total Taxes': 'إجمالي الضرائب',
      'Total Deductables': 'إجمالي الخصومات',
      
      // Adjustment Type translations
      'Tax': 'ضريبة',
      'Fee': 'رسوم',
      'Cashback': 'استرداد نقدي',
      'Commission': 'عمولة',
      'Discount': 'خصم',
      
      // Adjustment Direction translations
      'Increase': 'زيادة',
      'Decrease': 'نقصان',
      
      // Adjustment Applies To translations
      'Sender': 'المرسل',
      'Receiver': 'المستقبل',
      'System': 'النظام',
      
      // Calculation Type translations
      'Fixed': 'ثابت',
      'Percentage': 'نسبة مئوية',
      
      // Freshio Business Menu Items
      'Dashboard': 'لوحة التحكم',
      'Items': 'الأصناف',
      'Inventory': 'المخزون',
      'Purchases': 'المشتريات',
      'Sales Orders': 'أوامر البيع',
      'Stock Shortages': 'نواقص المخزون',
      'Waste': 'الهدر',
      'Delivery Routes': 'طرق التوصيل',
      
      // Actions
      'Actions': 'الإجراءات',
      
      // BOQ and Projects
      'BOQs': 'المقايسات',
      'Purchase Orders': 'أوامر الشراء',
      'Projects': 'المشاريع',
      'Requests For Quotation': 'طلبات عروض الأسعار',
      'Offers': 'العروض',
      'Quantity Surveying': 'حصر الكميات',
      'Project Invoices': 'فواتير المشاريع',
      'Project Category': 'فئة المشروع',
      'Cycles': 'الدورات',
      'Cycle Steps': 'خطوات الدورة',
      
      // Common UI Elements
      'Total Inventory Cost:': 'إجمالي تكلفة المخزون:',
      'Total Cost': 'التكلفة الإجمالية',
      'Avg Cost': 'متوسط التكلفة',
      'Available Qty': 'الكمية المتاحة',
      'Item Name': 'اسم الصنف',
      'Unit Price': 'سعر الوحدة',
      'Requested Qty': 'الكمية المطلوبة',
      'Approved Qty': 'الكمية المعتمدة',
      'Order Items': 'أصناف الأوردر',
      'Purchase Items': 'أصناف الشراء',
      'Profit': 'الربح',
      
      // Order Status
      'Approved': 'مقبول',
      'Partially Approved': 'مقبول جزئياً',
    };
    const arabicNumber = String(englishText).replace(/[0-9]/g, (match) => {
      return translations[match];
    });
    if(languageFactor == 'ar') {
      return translations[englishText] || arabicNumber
    }else {
      return englishText
    }
  }
}
