export interface RequiredDropDown{
    Account?: boolean;
    Entity?: boolean;
    Project?: boolean;
    Contract?: boolean;
    Assets?: boolean;
    Invoices?: boolean;
    CostCenter?: boolean;
    CompanyID: number;
    AccountID: number;
    Units?: boolean;
    Resources?: boolean;
    Banks?: boolean;
    BankBranches?: boolean;
    TreasuryAndBankAcc?: boolean;
    AccountType?: boolean;
    ParentAccount?: boolean;
    OutgoingClassification?: boolean;
    ChequeBook?: boolean;
    FieldName?: boolean;
    Users?: boolean;
    CategoryAssets?: boolean;
    Currency?: boolean;
    BOQ?: boolean;
    DeductAndTaxType?: boolean;
    DeductAndTaxStandard?: boolean;
    Journal?: boolean;
    Activity?: boolean;
    Cycle?: boolean;
    Vendor?: boolean;
    ResourceCategory?: boolean;
    JobOrder?: boolean;
    InvoiceCycle?: boolean;
    Industry?: boolean;
    Actvity?: boolean; // Assuming this is not a typo
    Country?: boolean;
    City?: boolean;
    RoleClassification?: boolean;
    PersonContact?: boolean;
    Warehouses?: boolean;
    RececivingEntity?: boolean;
    BOQItemLink?: boolean;
    RequestCategory?: boolean;
    NeedRequestCategory?: boolean;
    Location?: boolean;
    ActivityTemplate?: boolean;
    TreasuryBankAccount?:boolean;
    IncomeClassification?:boolean;
    TreasuryType?:boolean;
    ReceivableCheques?:boolean;
    PayableCheques?:boolean;
    Governorate?:boolean;
    District?:boolean;
    Branch?:boolean;
    Department?:boolean;
    Position?:boolean;
}
