export interface ReturnedDropDown {
    AccountLookUp: any[];
    ProjectLookUP: any[];
    ContractsLookUP:any[];
    GovernorateLookUP:any[];
    DistrictLookUP:any[];
    DepartmentLookUP:any[];
    InvoicesLookUP: any[];
    CostCenterLookUP: any[];
    AssetsLookUP: any[];
    EntityLookUP: any[];
    UnitsLookUP: any[];
    ResourcesLookUP: any[];
    BankLookUP: any[];
    BankBranchesLookUP: any[];
    TreasuryAndBankAccLookUP:any[];
    AccountTypeLookUP: any[];
    OutgoingClassificationLookUP: any[];
    ChequeBookLookUP: any[];
    FieldNameLookUP: any[];
    UsersLookUP: any[];
    CategoryAssetsLookUP: any[];
    CurrencyLookUP:any[];
    BOQLookUP: any[];
    DeductAndTaxTypeLookUP: any[];
    DeductAndTaxStandardLookUP:any[];
    JournalLookUP: any[];
    ActivityLookUP: any[];
    CycleLookUP: any[];
    CityLookUP: any[];
    VendorLookUP: any[];
    ResourceCategoryLookUP: any[];
    JobOrderLookUP: any[];
    IndustryLookUP: any[];
    CountryLookUP: any[];
    RoleClassificationLookUP: any[];
    PersonContactLookUP:any[];
    WarehousesLookUP:any[];
    RequestCategoryLookUP: any[];
    NeedRequestCategoryLookUP: any[];
    LocationLookUP: any[];
    BranchLookUP: any[];
    ActivityTemplateLookUP: any[];
    TreasuryBankAccountLookUP:any[];
    IncomeClassificationLookUP:any[];
    TreasuryTypeLookUP:any[];
    ReceivableChequesLookUP:any[];
    PayableChequesLookUP:any[];
    PositionLookUP:any[];
  }
